### ISSUE TITLE
Can't run "make" or "make install"

### ISSUE THREAD

**Issue by ghost** [IanusInferus/termux-mono#1]
When I'm trying to run "make" or "make install", i get this:

make[4]: Entering directory '/data/data/com.termux/files/home/mono-6.8.0.105/mono/utils'
  CC       libmonoutils_la-mono-rand.lo
mono-rand.c:67:22: error: implicit declaration of
      function 'getrandom' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
                gssize const err = getrandom (bu...
                                   ^
1 error generated.
make[4]: *** [Makefile:1744: libmonoutils_la-mono-rand.lo] Error 1
make[4]: Leaving directory '/data/data/com.termux/files/home/mono-6.8.0.105/mono/utils'
make[3]: *** [Makefile:1917: install-recursive] Error 1
make[3]: Leaving directory '/data/data/com.termux/files/home/mono-6.8.0.105/mono/utils'
make[2]: *** [Makefile:2077: install] Error 2
make[2]: Leaving directory '/data/data/com.termux/files/home/mono-6.8.0.105/mono/utils'
make[1]: *** [Makefile:523: install-recursive] Error 1
make[1]: Leaving directory '/data/data/com.termux/files/home/mono-6.8.0.105/mono'
make: *** [Makefile:603: install-recursive] Error 1

**Comment by IanusInferus** [comment]
Maybe it's missing getrandom function and autoconf has not detected it correctly. You can try edit config.h and change

    #define HAVE_GETRANDOM 1

to

    /* #undef HAVE_GETRANDOM */

before running make.

**Comment by IanusInferus** [comment]
You can also try the new guide in which autoconf can correctly detect the existence of these C functions.
