### ISSUE TITLE
Running nuget

### ISSUE THREAD

**Issue by ravener** [IanusInferus/termux-mono#10]
Is it possible to run NuGet?

I downloaded nuget.exe and ran it but I keep getting a weird error that google doesn't have any useful results.

```
~/mono  mono --runtime=v4.0 nuget.exe install Newtonsoft.Json
Feeds used:
  https://api.nuget.org/v3/index.json

Installing package 'Newtonsoft.Json' to '/data/data/com.termux/files/home/mono'.
Unable to load the service index for source https://api.nuget.org/v3/index.json.
  The type initializer for 'NuGet.Configuration.ProxyCache' threw an exception.
  libc.so.6 assembly:<unknown assembly> type:<unknown type> member:(null)
```

**Comment by IanusInferus** [comment]
Have you created a libc.so.6 symbol link in a library search path?

    ln -s /system/lib64/libc.so /data/data/com.termux/files/usr/local/lib/libc.so.6

**Comment by IanusInferus** [comment]
By the way, recent versions of Newtonsoft.Json shifted from original JSON specification with features such as time guessing even with string type rather than DateTime type, which cause data loss in round-tripping. I used it previously but have migrated.

**Comment by ravener** [comment]
I don't plan to use that lib atm. was just testing nuget. 

Also libc.so.6 already came symlinked when i extracted the tar but now that i check it it's apparently a broken symlink. You might wanna fix that as lib64 does not exist on armv7, it should be lib, lemme fix that symlink and try again

**Comment by IanusInferus** [comment]
Emm.. I haven't noticed that. I'll fix it soon.

**Comment by ravener** [comment]
So now i'm past the libc error and now i have ssl errors

```
✘  ~/mono  mono --runtime=v4.0 nuget.exe install Newtonsoft.Json   Feeds used:
  https://api.nuget.org/v3/index.json

Installing package 'Newtonsoft.Json' to '/data/data/com.termux/files/home/mono'.
Unable to load the service index for source https://api.nuget.org/v3/index.json.
  The SSL connection could not be established, see inner exception.
  Authentication failed, see inner exception.
  Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
    at /tmp/mono/mono-6.12.0.122/external/boringssl/ssl/handshake_client.c:1132
```
Everyone on the internet is recommending to use `cert-sync` but i'm not sure if that's relevant for android, any ideas?

**Comment by IanusInferus** [comment]
Android have put the system certificate store at  `/system/etc/security/cacerts`, and it appears only once in mono source code at `mcs/class/System/Mono.Btls/MonoBtlsProvider.cs`.
So mono can use the system certificate store and don't need `cert-sync`.
I think you need to patch that file by defining MONODROID at top and recompiling System.dll.

**Comment by ravener** [comment]
Mono needs it's own certificates or so. This is the exact issue i'm facing i think https://github.com/mono/mono/issues/12406

**Comment by IanusInferus** [comment]
I have found that mono certificate store path is at `~/.config/.mono/certs`, `/usr/share/.mono/certs`.

https://stackoverflow.com/questions/25918024/how-to-delete-remove-certificates-from-mono-certificate-stores-my-and-trust/25919240
https://github.com/mono/mono/blob/main/man/mono.1

The later is a readonly path on Android. I think you can copy files from `/usr/share/.mono/certs` on a PC with mono to `~/.config/.mono/certs` on Android.

**Comment by ravener** [comment]
Thank You. I copied over those certs from an Ubuntu VPS and it fixed it. Finally NuGet is working. 

P.S i also had the copy the `new-certs` (`/usr/share/.mono/new-certs`) folder too, just `certs` wasn't enough.
