### ISSUE TITLE
Installing to /data/data/com.termux/files/usr

### ISSUE THREAD

**Issue by leap0x7b** [IanusInferus/termux-mono#11]
Hi, can i install mono on /data/data/com.termux/files/usr? I used to it and i dont want mono libraries and executables in /data/data/com.termux/files/usr/local.

**Comment by IanusInferus** [comment]
You can move files from /data/data/com.termux/files/usr/local to /data/data/com.termux/files/usr. They are compiled with a relative rpath, so they can be moved. (For Api Level < 24, LD_LIBRARY_PATH may also need to be adjusted.)

But as the compiled binaries are not managed by a package manager, you will find it difficult to uninstall or update to a new version. You can create a file list for these situations.

**Comment by leap0x7b** [comment]
Thanks
