### ISSUE TITLE
cannot unpack data.tar

### ISSUE THREAD

**Issue by Aevus-Eye** [IanusInferus/termux-mono#12]
when I try to unpack `data.tar` from the downloaded `msbuild_16.6+xamarinxplat.2021.01.15.16.11-0xamarin1+ubuntu2004b1_all.deb`, it throws this error:
```
tar xf data.tar
tar: ./usr/lib/mono/msbuild/Current/bin/System.Reflection.Metadata.dll: Cannot create symlink to 'Roslyn/System.Reflection.Metadata.dll': No such file or directory
tar: Exiting with failure status due to previous errors
```

I am using windows 10 and have visual studio 2019 with the .NET extension installed.

**Comment by IanusInferus** [comment]
It looks related to symbolic links.
Are you using the system tar.exe or tar in WSL? If you are using the system tar.exe, you can try tar in WSL.
Non-NTFS file system or /mnt/x/... directories may also matter. You can try to extract to the internal file system of WSL.

**Comment by Aevus-Eye** [comment]
I tried it in wsl and tar ran without giving any output to the console and finished with exit code 0. but when i navigate to the `lib/mono/msbuild/Current/bin/System.Reflection.Metadata.dll` file it shows up as a broken link.
![grafik](https://user-images.githubusercontent.com/42070251/121696782-b5f7ff00-cacc-11eb-8c8b-00a1b6d10e32.png)


also the folder `mono-6.12.0.122-bin/data/data/com.termux/files/usr/local/lib/mono/msbuild/Current/bin/` does not contain a `Roslyn` folder, so i cannot run these commands 
```
sed -i 's|"@(Compile)"|"@(Compile);/parallel-"|g' mono-6.12.0.122-bin/data/data/com.termux/files/usr/local/lib/mono/msbuild/Current/bin/Roslyn/Microsoft.CSharp.Core.targets
sed -i 's|"@(Compile)"|"@(Compile);/parallel-"|g' mono-6.12.0.122-bin/data/data/com.termux/files/usr/local/lib/mono/msbuild/Current/bin/Roslyn/Microsoft.VisualBasic.Core.targets
```

i ran all of the commands inside WSL with Ubuntu 20.04

I still tried to move everything into termux, but in the end the `usr/local/bin` directory only contains `msbuild` and no `mono`

**Comment by IanusInferus** [comment]
The folder `Roslyn` is from the mono build result. You need to copy MSBuild files over mono build result with

    cp -R usr/* mono-6.12.0.122-bin/data/data/com.termux/files/usr/local/

**Comment by IanusInferus** [comment]
The MSBuild package `msbuild_16.6+xamarinxplat.2021.01.15.16.11-0xamarin1+ubuntu2004b1_all.deb` doesn't contain mono runtime.

**Comment by Aevus-Eye** [comment]
I'm sorry, there has been a missunderstanding on my part. I thought that 

> Don't try to build from source, it depends on a .Net Core version which is not shipped with Visual Studio and is very difficult to compile both on Windows or on Linux. Just download the pre-compiled binary from Mono. It contains only portable .Net binaries.

from the `Install MSBuild` section was refering to the `Build Mono from source` section, so i thought i could skip building mono from source and just install the prebuilt binarys. 
I have now built mono from source and everything works now.
