### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by OilSubjectLoss7** [IanusInferus/termux-mono#13]

**Comment by IanusInferus** [comment]
The executables are installed under `/data/data/com.termux/files/usr/local`. You can delete it if you haven't installed other custom-compiled programs. Or you can check the file list in the tarball (ex. mono-termux.6.12.0.122-arm64-android24.tar.xz) to get a list of files to delete.

Then you can remove the relevant exports in ~/.bash_profile.
