### ISSUE TITLE
Msbuild produces unusable binaries

### ISSUE THREAD

**Issue by AbdullahM0hamed** [IanusInferus/termux-mono#3]
So, I'm attempting to compile [this project](https://github.com/LagradOst/Cloudstream-2-Console) using msbuild - and for some reason, the generated file is an ELF (as opposed to being a file I could run with mono) - and won't execute at all, am I doing something wrong here?

I first ran:
`~/arch/startarch c nuget restore *.csproj`, and afterwards ran `msbuild` - which generated the non-functional 'bin/Debug/netcoreapp3.1/CloudStream2Console' file.

**Comment by IanusInferus** [comment]
I haven't tried .Net Core on termux-mono. I have only tested programs targeting .Net Framework 4.5. Maybe the msbuild shipped by mono is different from the official one.
.Net Core supports ARM64 officially. You may try to use it in a prooted Linux.
