### ISSUE TITLE
Mono not found?

### ISSUE THREAD

**Issue by chakibchemso** [IanusInferus/termux-mono#4]
Hi

I did everything as described
but calling mono won't work even after adding local/bin to path
So I navigated into it manually and it won't execute :
Can't execute binary file
Calling msbuild works but :
Mono not found
Is it compiled for arm64?
I'm on arm64 cpu and arm system image (I know it's a dumb move Samsung)
And I can't root or flash a x64 vendor & rom right now :/

**Comment by chakibchemso** [comment]
![Screenshot_20201012-212537_Termux](https://user-images.githubusercontent.com/41765106/95787514-92787c80-0cd1-11eb-91f9-1023414879fc.jpg)

**Comment by IanusInferus** [comment]
The prebuilt releases are for Arm64 and Android Api Level 24 (7.0 or later).
Arm64 CPU can run arm binary. An arm system image can only run arm binary and not arm64 binary.
You'll need to compile from source.
Replace '--target=aarch64-linux-androideabi24' with '--target=armv7a-linux-androideabi24' and '--host=aarch64-linux-androideabi24' with '--host=armv7a-linux-androideabi24'.
The Android Api Level is also important if your system is below Android 7.0. Check it at https://source.android.com/setup/start/build-numbers
And replace 24 in '--target=armv7a-linux-androideabi24', '--host=armv7a-linux-androideabi24', '--with-btls-android-api=24' to the api level you need.

**Comment by chakibchemso** [comment]
@IanusInferus hi
I'm on Android 10 so yup it's the arm stock ROM I'm on
It's so dumb they packed a phone with 32bit image and 64bit processor (Samsung galaxy J6)
I'm on stock recovery so I can't flash 64bit vendor :/
So can u compile arm 32 binaries cz I'm far from my house for a while
Thx for the great work btw

**Comment by IanusInferus** [comment]
Can you try https://github.com/IanusInferus/termux-mono/releases/download/untagged-ffb0dba34216f77e95de/mono-termux.6.12.0.90-armv7a.tar.xz and check if it works?

**Comment by chakibchemso** [comment]
404 not found
The latest build is 6.10 in the repo

**Comment by IanusInferus** [comment]
Can you try https://github.com/IanusInferus/termux-mono/releases/download/v20201014/mono-termux.6.12.0.90-armv7a.tar.xz ?
It looks like that the file needs to be published to be seen.

**Comment by chakibchemso** [comment]
Thx ❤️ that's working
Now I'll try to recompile my game's DLL and see if the modified code will work 👍
![Screenshot_20201016-212038_Termux](https://user-images.githubusercontent.com/41765106/96305355-ac79ce00-0ff5-11eb-9119-3b729cfddf7f.jpg)

**Comment by chakibchemso** [comment]
I'm getting this error and it's pointless cz unity doesn't depend on nuget packages or any dependencies sort of things
All the unity DLLs are present in the same dir as csproj
![Screenshot_20201016-235912_Termux](https://user-images.githubusercontent.com/41765106/96321124-3896f000-100c-11eb-9db5-13ad2c29ead9.jpg)

**Comment by IanusInferus** [comment]
Your project looks like a .Net Core project (which uses Microsoft.NET.Sdk) and .Net Core projects use nuget implicitly for system libraries.
You can check the project file.
A .Net Framework project starts with

    <?xml version="1.0" encoding="utf-8"?>
    <Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

A .Net Core project starts with

    <Project>
        <PropertyGroup>

You may need to change Unity .Net profile from .NET Standard 2.0 to .NET 4.x.
I don't know whether .Net Core projects are supported on Mono and Mono's version of MSBuild, but it is generally easier to use .Net Framework projects on Mono.

**Comment by elkolya** [comment]
Great, keep it up.
Not really an issue but would like to ask how to create csharp solution folder with this as the "dotnet new" does in the command line.
Thanks.

**Comment by IanusInferus** [comment]
This repository is mainly maintained for traditional mono (without .Net Core).
As Microsoft has stated "Since the .NET Core and Mono runtimes have a lot of similarities, CoreCLR and Mono will be drop-in replacements for one another. Developers will be able to switch to choose between the different runtime options." (https://blog.hildenco.com/2019/05/net-core-and-net-merging-as-net-50.html) and is "Consolidating .NET GitHub repos" (https://github.com/dotnet/announcements/issues/119), I think there may be some kind of refactoring going, especially considering that mono has not released new features for half a year.
.Net 5 has Windows ARM64 support now (https://devblogs.microsoft.com/dotnet/announcing-net-5-0/), and it's clear that they are going to support Linux ARM64 (https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md). It's not very difficult to support Android ARM64 after that.
Eventually, we may be able to compile .Net 5 or later directly for Android or compile a new version of mono that is almost the same as .Net 5.
Personally, I have not been actively developing with .Net Core or .Net 5 yet. I am still waiting for a good time to switch.
I think the uncertainty will be resolved in the coming months.

**Comment by IanusInferus** [comment]
To create a C# solution for .Net Framework, we generally use Visual Studio (there is a community version). For Unity projects, the Unity Editor will create a cspoj file for you.

**Comment by elkolya** [comment]
> This repository is mainly maintained for traditional mono (without .Net Core).
> As Microsoft has stated "Since the .NET Core and Mono runtimes have a lot of similarities, CoreCLR and Mono will be drop-in replacements for one another. Developers will be able to switch to choose between the different runtime options." (https://blog.hildenco.com/2019/05/net-core-and-net-merging-as-net-50.html) and is "Consolidating .NET GitHub repos" ([dotnet/announcements#119](https://github.com/dotnet/announcements/issues/119)), I think there may be some kind of refactoring going, especially considering that mono has not released new features for half a year.
> .Net 5 has Windows ARM64 support now (https://devblogs.microsoft.com/dotnet/announcing-net-5-0/), and it's clear that they are going to support Linux ARM64 (https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md). It's not very difficult to support Android ARM64 after that.
> Eventually, we may be able to compile .Net 5 or later directly for Android or compile a new version of mono that is almost the same as .Net 5.
> Personally, I have not been actively developing with .Net Core or .Net 5 yet. I am still waiting for a good time to switch.
> I think the uncertainty will be resolved in the coming months.

Well explained, hopefully we can wait for Microsoft for better results on this.

**Comment by elkolya** [comment]
> To create a C# solution for .Net Framework, we generally use Visual Studio (there is a community version). For Unity projects, the Unity Editor will create a cspoj file for you.

Only for gui? there's no possible command line to create cspoj using mono or msbuild?

**Comment by IanusInferus** [comment]
> 
> 
> > To create a C# solution for .Net Framework, we generally use Visual Studio (there is a community version). For Unity projects, the Unity Editor will create a cspoj file for you.
> 
> Only for gui? there's no possible command line to create cspoj using mono or msbuild?

I haven't heard of any command to do this using mono or msbuild.
Theoretically you can create a csproj file from scratch as it is just a xml file. Microsoft even has a guide at https://docs.microsoft.com/en-us/visualstudio/msbuild/walkthrough-creating-an-msbuild-project-file-from-scratch?view=vs-2019 .
But this is very unpractical. It is better to copy an existing one and modify its text.
