### ISSUE TITLE
armv7 

### ISSUE THREAD

**Issue by sqbitz** [IanusInferus/termux-mono#6]
I downloaded mono-termux.6.12.0.90-armv7a-androideabi21.tar.xz from releases and extracted per the instructions, but when I run mono I get
$ mono
CANNOT LINK EXECUTABLE "mono": library "libmonosgen-2.0.so" not found
Aborted

Any ideas?  Thanks!

Environment is
$ uname -a
Linux localhost 3.18.71-perf+ #1 SMP PREEMPT Fri Aug 14 16:22:30 KST 2020 armv7l Android

**Comment by IanusInferus** [comment]
Have you added /data/data/com.termux/files/usr/local/lib to environment variable LD_LIBRARY_PATH? It is necessary on API Level < 24, and as the armv7a package is built for API Level 21, it is necessary on all arm7va devices regardless of runtime API Levels.

    echo export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/local/lib:$LD_LIBRARY_PATH >> ~/.bash_profile

**Comment by sqbitz** [comment]
Thank you for the quick reply! I feel kinda stupid now.  Your instructions clearly say to do that and I just missed it.  Works correctly now.  Thanks again!
