### ISSUE TITLE
cannot pass the ./configure

### ISSUE THREAD

**Issue by mxpro1996** [IanusInferus/termux-mono#8]
When executing below
`./configure --host=$arch --prefix=/data/data/com.termux/files/usr/local --disable-mcs-build --with-btls-android-ndk="$(realpath ..)/android-ndk-r21e" --with-btls-android-api=$api_level --with-btls-android-cmake-toolchain="$(realpath ..)/android-ndk-r21e/build/cmake/android.toolchain.cmake" $extra_flags`
I get this error
![IMG_20210322_161432](https://user-images.githubusercontent.com/73088482/111959726-cd58c900-8b29-11eb-8d91-7bf7aeb331cd.jpg)

**Comment by IanusInferus** [comment]
Do you run the command line on your phone? The build process is meant to be run on PC.
If you need to run the build process on an aarch64 device, you need to get a corresponding ndk, such as https://github.com/Lzhiyong/termux-ndk (unofficial).

**Comment by mxpro1996** [comment]
> Do you run the command line on your phone? The build process is meant to be run on PC.
> If you need to run the build process on an aarch64 device, you need to get a corresponding ndk, such as https://github.com/Lzhiyong/termux-ndk (unofficial).

Actually,I execute it on a x86 platfrom docker,may the problem is related to it?
![IMG_20210322_175427](https://user-images.githubusercontent.com/73088482/111971815-b7520500-8b37-11eb-8f4f-546d9a397909.jpg)

**Comment by IanusInferus** [comment]
The error message 'Pthreads not supported by the GC on this platform' is located in external/bdwgc/configure.ac.
I think it's failed in compiling a test with pthread.
I don't know why it failed but you can try ignoring the error by commenting out the case branch with the error message.

**Comment by mxpro1996** [comment]
> The error message 'Pthreads not supported by the GC on this platform' is located in external/bdwgc/configure.ac.
> I think it's failed in compiling a test with pthread.
> I don't know why it failed but you can try ignoring the error by commenting out the case branch with the error message.

After ignoring the error,the ./configure can be successfully passed.
Unfortunately the "make" will be interrupted by some clang standard problems,setting std=gnu99 can ignore those,but will fail due to "cannot find -lpthread".
I guess that there is a problem with okteto's docker,maybe linux kernel.Now I try to build it with my laptop.If time permits,can you try it on okteto's docker?

**Comment by IanusInferus** [comment]
I haven't seen a Linux system lacking pthread. It shouldn't be a kernel problem.
Maybe it's some kind of system path resolution problems or compiler problems.
You can try THREADDLLIBS="-pthread" .

I don't happen to use okteto, so you are on your own.

**Comment by mxpro1996** [comment]
> I haven't seen a Linux system lacking pthread. It shouldn't be a kernel problem.
> Maybe it's some kind of system path resolution problems or compiler problems.
> You can try THREADDLLIBS="-pthread" .
> 
> I don't happen to use okteto, so you are on your own.

Thanks!

**Comment by mxpro1996** [comment]
😭Both failed to build on my laptop running Ubuntu 20.04.Maybe the build guide needs to be modified?

**Comment by IanusInferus** [comment]
What errors have you encountered?

**Comment by mxpro1996** [comment]
> What errors have you encountered?

Same as last time.

**Comment by IanusInferus** [comment]
I have compiled mono-6.12.0.122 on Ubuntu 20.04 with NDK r22 and haven't encountered this problem.

**Comment by IanusInferus** [comment]
I have also added a prebuilt version for Android arm64 API Level 21. Please check https://github.com/IanusInferus/termux-mono/releases/tag/v20210327

**Comment by mxpro1996** [comment]
> I have also added a prebuilt version for Android arm64 API Level 21. Please check https://github.com/IanusInferus/termux-mono/releases/tag/v20210327

Thanks!
It works well on my aarch64 device running Android_5.1.
In regard to the error mentioned at this issue,I plan to try again with NDK r22 as your guide.

**Comment by mxpro1996** [comment]
> > I have also added a prebuilt version for Android arm64 API Level 21. Please check https://github.com/IanusInferus/termux-mono/releases/tag/v20210327
> 
> Thanks!
> It works well on my aarch64 device running Android_5.1.
> In regard to the error mentioned at this issue,I plan to try again with NDK r22 as your guide.

Thanks!
Successfully pass the "./configure" and build mono with new build guide.

**Comment by mxpro1996** [comment]
Close.
