### ISSUE TITLE
armv7 builds for api level 24+

### ISSUE THREAD

**Issue by ravener** [IanusInferus/termux-mono#9]
Can we get prebuilt releases for api level 24+ ?

Will be the api level 21 still run under higher versions?

**Comment by IanusInferus** [comment]
The one for api level 21 runs on 21+, including 24+.
But, there is a drawback that we need to add

    export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/local/lib:$LD_LIBRARY_PATH

to ~/.bash_profile as "-Wl,-rpath='\$\$ORIGIN/../lib' -Wl,--enable-new-dtags" is only supported on 24+ and is disabled.

**Comment by ravener** [comment]
ah ok, thank you. I will give it a try in a bit after i free up some storage first. Mind telling me how much space does the extracted files take?

**Comment by IanusInferus** [comment]
"-rpath" with $ORIGIN enables relative library load path, which let us be able to move mono directory around.

Sorry, I have deleted the temporary files and haven't checked the space.

**Comment by ravener** [comment]
One last question. Why does it look you packaged multiple mono versions in one. Is that expected?

**Comment by IanusInferus** [comment]
The different packages are for different CPU architectures (arm64 and armv7a) or different Android Api Levels (24+, 21+).
They are all compiled from the same mono version.

**Comment by ravener** [comment]
No not the release archives. but when i'm extracting i keep seeing folders with version `4.7` and more directories like `4.6.2` and some `4.8` and so on.

**Comment by IanusInferus** [comment]
I think they are mono's API stubs for building .Net code.

**Comment by ravener** [comment]
ok thanks i managed to get it working
